"""add competitions monitor state table

Revision ID: 57b7ecd0f248
Revises: d22b3ccb345c
Create Date: 2026-07-30 18:04:19.986645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "57b7ecd0f248"
down_revision: Union[str, Sequence[str], None] = "d22b3ccb345c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions_monitor_state",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("event_code", sa.String(), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("registration_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_code"),
    )
    op.add_column(
        "users",
        sa.Column(
            "competitions_notifications",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "competitions_notifications")
    op.drop_table("competitions_monitor_state")
    # ### end Alembic commands ###
