"""add workout table

Revision ID: 8f4bd1156143
Revises: 8df7eb14c0f6
Create Date: 2026-03-10 18:50:56.334903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4bd1156143'
down_revision: Union[str, Sequence[str], None] = '8df7eb14c0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('notifications', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'notifications', 'workouts', ['workout_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('workouts')
    # ### end Alembic commands ###
