"""add notifications_enabled on User model

Revision ID: 92e020e9a307
Revises: 3c1b294e7f33
Create Date: 2026-05-18 15:33:18.468553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e020e9a307'
down_revision: Union[str, Sequence[str], None] = '3c1b294e7f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    # ### end Alembic commands ###
