"""add site_user_id on users

Revision ID: bb307b105828
Revises: 8f4bd1156143
Create Date: 2026-03-19 20:17:05.840647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb307b105828'
down_revision: Union[str, Sequence[str], None] = '8f4bd1156143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('site_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'site_user_id')
    # ### end Alembic commands ###
