"""added unique constraints, index, changed foreign keys, removed notifications_rules.only_enabled, added workouts.user_id and title and workout_type

Revision ID: cefc449d7610
Revises: 92e020e9a307
Create Date: 2026-06-08 13:28:18.258006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cefc449d7610"
down_revision: Union[str, Sequence[str], None] = "92e020e9a307"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(
        "uq_notification_workout_rule", "notifications", ["workout_id", "rule_id"]
    )
    op.drop_constraint(
        op.f("notifications_rule_id_fkey"), "notifications", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("notifications_workout_id_fkey"), "notifications", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("notifications_user_id_fkey"), "notifications", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "notifications", "workouts", ["workout_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "notifications",
        "notifications_rules",
        ["rule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "notifications", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(
        "uq_notifications_rules_default",
        "notifications_rules",
        ["user_id", "offset_minutes"],
        unique=True,
        postgresql_where=sa.text("workout_id IS NULL"),
    )
    op.create_unique_constraint(
        "uq_notifications_rules_specific",
        "notifications_rules",
        ["user_id", "workout_id", "offset_minutes"],
    )
    op.drop_constraint(
        op.f("notifications_rules_user_id_fkey"),
        "notifications_rules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "notifications_rules", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("notifications_rules", "only_enabled")
    op.add_column("workouts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.add_column(
        "workouts", sa.Column("site_workout_id", sa.Integer(), nullable=False)
    )
    op.add_column("workouts", sa.Column("title", sa.String(), nullable=True))
    op.add_column("workouts", sa.Column("workout_type", sa.String(), nullable=True))
    op.create_unique_constraint(None, "workouts", ["site_workout_id"])
    op.create_foreign_key(
        None, "workouts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("workouts", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "workouts", type_="foreignkey")
    op.drop_constraint(None, "workouts", type_="unique")
    op.drop_column("workouts", "workout_type")
    op.drop_column("workouts", "title")
    op.drop_column("workouts", "site_workout_id")
    op.drop_column("workouts", "user_id")
    op.add_column(
        "notifications_rules",
        sa.Column("only_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "notifications_rules", type_="foreignkey")
    op.create_foreign_key(
        op.f("notifications_rules_user_id_fkey"),
        "notifications_rules",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_notifications_rules_specific", "notifications_rules", type_="unique"
    )
    op.drop_index(
        "uq_notifications_rules_default",
        table_name="notifications_rules",
        postgresql_where=sa.text("workout_id IS NULL"),
    )
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("notifications_user_id_fkey"),
        "notifications",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("notifications_workout_id_fkey"),
        "notifications",
        "workouts",
        ["workout_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("notifications_rule_id_fkey"),
        "notifications",
        "notifications_rules",
        ["rule_id"],
        ["id"],
    )
    op.drop_constraint("uq_notification_workout_rule", "notifications", type_="unique")
    op.drop_table("processed_events")
    # ### end Alembic commands ###
